site_name: Mkdocs 2DAW
nav:
    - Inici: 'index.md'

    - 'Manga': 'manga.md'
    - 'Anime': 'anime.md'
    - 'Estudios': 'estudios.md'
    - 'Directores': 'directores.md'
    - 'Mangakas': 'mangakas.md'

theme: readthedocs
